version: '3'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: judo-club-wallers
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
  mail:
    image: dockage/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"
volumes:
  db-data: